config/routes.rb
Rails.application.routes.draw do
  get 'home/main'
  # Devise routes for User

  devise_for :users, skip: :registrations, controllers: {
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get 'customers/sign_up', to: 'customers/registrations#new', as: :new_customer_registration
    get 'edit_customer_login', to: 'customers/registrations#edit', as: :edit_customer_registration

    post 'customers', to: 'customers/registrations#create', as: :customer_registration
    put 'customers', to: 'customers/registrations#update'
    delete 'customers', to: 'customers/registrations#destroy'


    get 'owners/sign_up', to: 'owners/registrations#new', as: :new_owner_registration
    get 'edit_owner_login', to: 'owners/registrations#edit', as: :edit_owner_registration

    post 'owners', to: 'owners/registrations#create', as: :owner_registration
    put 'owners', to: 'owners/registrations#update'
    delete 'owners', to: 'owners/registrations#destroy'

  end


  # Health check route
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Root route
  # root 'browse#index'
  get 'home', to: 'home#main'
  root 'home#main'

  # resources :orders do
  #   member do
  #     patch :update_status

  #   end
  # end

  resources :orders, only: [:index, :show]
  patch 'orders/:id/update_status', to: 'orders#update_status', as: :update_status

  # Browse routes
  get 'restaurants', to: 'browse#index'
  get 'restaurants/:id', to: 'browse#show', as: :restaurant

  # Restaurant routes with nested resources for menu_items and reviews
  # resources :restaurants do
  #   resources :menu_items, only: [:index, :new, :create, :edit, :update, :destroy]
  #   resources :reviews, only: [:index, :new, :create, :edit, :update, :destroy]
  # end

  # Customer routes
  resources :customers, only: [:update, :show]
  resource :cart, only: [:show]
  get '/profile', to: 'profiles#show', as: :profile
  get '/edit_profile', to: 'profiles#edit', as: :edit_profile

  # MenuItems routes
  #resources :menu_items, only: [:show, :edit, :update, :destroy]

  # Defines the root path route ("/")
  # root "posts#index"
  resources :restaurants, only: [:index, :create, :update, :destroy] do
    resources :menu_items, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :reviews, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  get 'restaurants/:restaurant_id/customer_menu', to: 'menu_items#customer_index', as: :customer_menu
  post 'add_to_cart/:menu_item_id', to: 'cart_items#add_to_cart', as: :add_to_cart
  patch 'remove_from_cart/:menu_item_id', to: 'cart_items#remove_from_cart', as: :remove_from_cart
  get '/cartback', to: 'carts#back', as: :cart_back
  delete 'clear_cart', to: 'carts#clear_cart'

  # Owner path only
  get '/menu_items', to: 'menu_items#index'

  resource :checkout, only: [:create], controller: 'checkouts' do
    collection do
      get 'success', to: 'checkouts#success'
      get 'cancel', to: 'checkouts#cancel'
    end
  end

  get 'stripe_callback', to: 'stripe#callback'

  get 'owners/confirm', to: 'owners/registrations#confirm'
  get '*path', to: redirect('/home')

  resources :cart_items, only: [:create, :destroy]



end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :customer
  belongs_to :restaurant, optional: true
  has_many :cart_items, dependent: :destroy
  has_many :menu_items, through: :cart_items

  def clear_cart
    self.cart_items.destroy_all
    self.update(restaurant_id: nil)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    before_action :set_cart, only: [:show, :clear_cart]

    def show
        @cart_items = @cart.cart_items.includes(:menu_item)
    end

    def clear_cart

        @cart.cart_items.destroy_all
        @cart.update(restaurant_id: nil)
        flash[:notice] = 'Cart has been cleared'
        if params[:restaurant_id]
            redirect_to customer_menu_path(restaurant_id: params[:restaurant_id]), notice: 'Successfully cleared cart'
        else
            redirect_to cart_path, notice: 'Successfully cleared cart'
        end

    end

    def back
        begin
            @cart = Cart.find(params[:cart_id])
        rescue ActiveRecord::RecordNotFound
            redirect_to home_path
            return
        end
        if @cart.restaurant_id.nil?
            redirect_to home_path
        else
            redirect_to customer_menu_path(restaurant_id: @cart.cart_items.sample.menu_item.restaurant_id)
        end
    end

    private

    def set_cart
        @cart = current_user.customer.cart
    end
  end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<!-- app/views/carts/show.html.erb -->

<h1>Shopping Cart</h1>

<table>
  <thead>
    <tr>
      <th>Item Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Total</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
        <% if @cart_items.empty? %>
            <tr><td colspan="5">Your cart is empty.</td></tr>
        <% else %>
            <% @cart_items.each do |cart_item| %>
                <tr>
                <td><%= cart_item.menu_item.name %></td>
                <td>$<%= cart_item.menu_item.price %></td>
                <td><%= cart_item.quantity %></td>
                <td>$<%= cart_item.menu_item.price * cart_item.quantity %></td>
                <td>
                    <%= button_to 'Add', add_to_cart_path(menu_item_id: cart_item.menu_item.id, customer_id: current_user.customer.id), method: :post, class: 'btn btn-primary' %>
                    <%= button_to 'Remove', remove_from_cart_path(menu_item_id: cart_item.menu_item.id, customer_id: current_user.customer.id), method: :patch, class: 'btn btn-primary' %>
                </td>
                </tr>
            <% end %>
        <% end %>
  </tbody>
</table>

<div>
  <strong>Total:</strong> $<%= @cart_items.sum { |item| item.menu_item.price * item.quantity } %>
</div>

<div>
    <%= button_to 'Clear Cart', clear_cart_path, method: :delete, class: 'btn btn-warning' %>
</div>

<div>
    <%= button_to 'Checkout', checkout_path, method: :post, data: { turbo: false }, class: 'btn btn-warning' %>
</div>


<div>
    <%= link_to 'Back', cart_back_path(cart_id: @cart), class: 'btn btn-warning' %>
</div>