config/routes.rb
Rails.application.routes.draw do
  get 'home/main'
  # Devise routes for User

  devise_for :users, skip: :registrations, controllers: {
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get 'customers/sign_up', to: 'customers/registrations#new', as: :new_customer_registration
    get 'edit_customer_login', to: 'customers/registrations#edit', as: :edit_customer_registration

    post 'customers', to: 'customers/registrations#create', as: :customer_registration
    put 'customers', to: 'customers/registrations#update'
    delete 'customers', to: 'customers/registrations#destroy'


    get 'owners/sign_up', to: 'owners/registrations#new', as: :new_owner_registration
    get 'edit_owner_login', to: 'owners/registrations#edit', as: :edit_owner_registration

    post 'owners', to: 'owners/registrations#create', as: :owner_registration
    put 'owners', to: 'owners/registrations#update'
    delete 'owners', to: 'owners/registrations#destroy'

  end


  # Health check route
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Root route
  # root 'browse#index'
  get 'home', to: 'home#main'
  root 'home#main'

  # resources :orders do
  #   member do
  #     patch :update_status

  #   end
  # end

  resources :orders, only: [:index, :show]
  patch 'orders/:id/update_status', to: 'orders#update_status', as: :update_status

  # Browse routes
  get 'restaurants', to: 'browse#index'
  get 'restaurants/:id', to: 'browse#show', as: :restaurant

  # Restaurant routes with nested resources for menu_items and reviews
  # resources :restaurants do
  #   resources :menu_items, only: [:index, :new, :create, :edit, :update, :destroy]
  #   resources :reviews, only: [:index, :new, :create, :edit, :update, :destroy]
  # end

  # Customer routes
  resources :customers, only: [:update, :show]
  resource :cart, only: [:show]
  get '/profile', to: 'profiles#show', as: :profile
  get '/edit_profile', to: 'profiles#edit', as: :edit_profile

  # MenuItems routes
  #resources :menu_items, only: [:show, :edit, :update, :destroy]

  # Defines the root path route ("/")
  # root "posts#index"
  resources :restaurants, only: [:index, :create, :update, :destroy] do
    resources :menu_items, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :reviews, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  get 'restaurants/:restaurant_id/customer_menu', to: 'menu_items#customer_index', as: :customer_menu
  post 'add_to_cart/:menu_item_id', to: 'cart_items#add_to_cart', as: :add_to_cart
  patch 'remove_from_cart/:menu_item_id', to: 'cart_items#remove_from_cart', as: :remove_from_cart
  get '/cartback', to: 'carts#back', as: :cart_back
  delete 'clear_cart', to: 'carts#clear_cart'

  # Owner path only
  get '/menu_items', to: 'menu_items#index'

  resource :checkout, only: [:create], controller: 'checkouts' do
    collection do
      get 'success', to: 'checkouts#success'
      get 'cancel', to: 'checkouts#cancel'
    end
  end

  get 'stripe_callback', to: 'stripe#callback'

  get 'owners/confirm', to: 'owners/registrations#confirm'
  get '*path', to: redirect('/home')

  resources :cart_items, only: [:create, :destroy]



end

app/controllers/browse_controller.rb
class BrowseController < ApplicationController

  def index
    if current_user.is_restaurant?
      redirect_to home_path
      return
    end

    @restaurants = Restaurant.all

    # Sorting logic based on params
    case params[:sort]
    when 'location'
      if params[:order] == 'desc'
        @restaurants = @restaurants.order(address: :desc)
      else
        @restaurants = @restaurants.order(address: :asc)
      end
    # when 'operating_hours'
    #   @restaurants = @restaurants.sort_by { |restaurant| total_weekly_operating_hours(restaurant.operating_hours) }
    end
  end

  
  def show

    if current_user.is_restaurant?
      redirect_to home_path
      return
    end

    begin
        @restaurant = Restaurant.find(params[:id])
        @reviews = @restaurant.reviews.where.not(customer_id: current_user.customer.id).order(created_at: :desc).limit(5)
        # @reviews = @restaurant.reviews.order(created_at: :desc).limit(5)
        @spec_review = @restaurant.reviews.find_by(customer_id: current_user.customer.id)
        # if !@spec_review.nil?
        #   @reviews.delete(@spec_review)
        # end

        
    rescue ActiveRecord::RecordNotFound
        redirect_to home_path
    end
  end

  # def total_weekly_operating_hours(operating_hours)
  #   # Assuming format: 'Mon-Fri: 9am - 9pm'
  #   days, hours = operating_hours.split(': ')
  #   start_day, end_day = days.split('-').map { |day| Date::DAYNAMES.index(day.strip) }
  #   start_time, end_time = hours.split(' - ')
  
  #   # Convert times to 24-hour format
  #   start_hour = Time.parse(start_time).hour
  #   end_hour = Time.parse(end_time).hour
  
  #   # Adjust for overnight schedules
  #   end_hour += 24 if end_hour < start_hour
  
  #   # Calculate daily hours
  #   daily_hours = end_hour - start_hour
  
  #   # Adjust for week wrap-around
  #   total_days = start_day <= end_day ? (end_day - start_day + 1) : (7 - start_day + end_day + 1)
  
  #   total_days * daily_hours
  # rescue
  #   0 # Return 0 if there's any issue with parsing
  # end

  private

  # def time_until_closing(operating_hours)
  #     # Assuming operating_hours is in the format 'HH:MM - HH:MM'
  #     _, closing_time_str = operating_hours.split(' - ')
  #     closing_time = Time.parse(closing_time_str)

  #     # Calculate time until closing in minutes
  #     now = Time.now
  #     time_until_closing = (closing_time - now) / 60

  #     # Ensure the result is non-negative
  #     time_until_closing.negative? ? 0 : time_until_closing
  #   end
end

app/views/browse/index.html.erb
<!-- app/views/restaurants/index.html.erb -->

<div class="browse-container">
  <!-- Sidebar with menu buttons -->
  <div class="sidebar">
    <!-- Add your menu buttons here -->
    <% order = params[:sort] == 'location' && params[:order] != 'desc' ? 'desc' : 'asc' %>
    <%= link_to 'Sort by Location', restaurants_path(sort: 'location', order: order), class: 'menu-button' %>
    <!-- <button class="menu-button"><%= link_to 'Sort by Operating Hours', restaurants_path(sort: "operating_hours") %></button> -->
    <!-- Add more buttons as needed -->
  </div>

  <!-- Main content area with restaurant boxes -->
  <div class="main-content">
    <h1>Browse Restaurants</h1>

    <div class="restaurant-list">
      <% @restaurants.each do |restaurant| %>
        <%= link_to restaurant_path(restaurant), class: 'restaurant-box' do %>
          <div class="restaurant-image">
            <%= image_tag 'https://picsum.photos/300/200/?blur', class: 'card-image' %>
          </div>
          <div class="restaurant-details">
            <h2><%= restaurant.name %></h2>
            <p><strong>Address:</strong> <%= restaurant.address %></p>
            <p><strong>Phone Number:</strong> <%= restaurant.phone_number %></p>
            <p><strong>Operating Hours:</strong> <%= restaurant.operating_hours %></p>
            <!-- Add other restaurant information as needed -->
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<!-- Add links for user authentication -->
<!-- <% if user_signed_in? %>
  <%= button_to 'Sign out', destroy_user_session_path, method: :delete %>
  <%if current_user.role == 'customer'%>
     <%= link_to 'Profile', profile_path%>
  <%end%>
  <%if current_user.role == 'owner'%>
     <%= link_to 'Restaurant', restaurant_path(current_user.restaurant)%>
  <%end%>
  <%= csrf_meta_tags %>
  <p>Welcome, <%= current_user.email %></p> -->
<!-- this should be in nav bar -->

<% end %>

app/views/browse/show.html.erb
<%= render 'restaurants/rest_info'%>
<%= link_to 'View Menu', customer_menu_path(restaurant_id: @restaurant.id), class: 'btn btn-primary' %>
<h2>Reviews</h2>
<%if !@spec_review.nil?%>
    <div class="review">
    <p><strong>Customer:</strong> <%= @spec_review.customer.name %> </p>
    <p><strong>Rating:</strong> <%= @spec_review.rating %> Stars</p>
    <p><%= @spec_review.comment %></p>
    <p><%= @spec_review.recorded_date %></p>
    <%= link_to 'Edit Review', edit_restaurant_review_path(@restaurant, @spec_review), class: 'btn btn-primary' %>
    
  </div>
<%end%>
<% @reviews.each do |review| %>
  <div class="review">
    <p><strong>Customer:</strong> <%= review.customer.name %> Stars</p>
    <p><strong>Rating:</strong> <%= review.rating %> Stars</p>
    <p><%= review.comment %></p>
    <p><%= review.recorded_date %></p>
    
  </div>
<% end %>
<%= link_to 'Add New Review', new_restaurant_review_path(@restaurant.id), class: 'btn btn-primary' %>
<%= link_to 'View All Reviews', restaurant_reviews_path(@restaurant), class: 'btn btn-primary' %>