config/routes.rb
Rails.application.routes.draw do
  get 'home/main'
  # Devise routes for User

  devise_for :users, skip: :registrations, controllers: {
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get 'customers/sign_up', to: 'customers/registrations#new', as: :new_customer_registration
    get 'edit_customer_login', to: 'customers/registrations#edit', as: :edit_customer_registration

    post 'customers', to: 'customers/registrations#create', as: :customer_registration
    put 'customers', to: 'customers/registrations#update'
    delete 'customers', to: 'customers/registrations#destroy'


    get 'owners/sign_up', to: 'owners/registrations#new', as: :new_owner_registration
    get 'edit_owner_login', to: 'owners/registrations#edit', as: :edit_owner_registration

    post 'owners', to: 'owners/registrations#create', as: :owner_registration
    put 'owners', to: 'owners/registrations#update'
    delete 'owners', to: 'owners/registrations#destroy'

  end


  # Health check route
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Root route
  # root 'browse#index'
  get 'home', to: 'home#main'
  root 'home#main'

  # resources :orders do
  #   member do
  #     patch :update_status

  #   end
  # end

  resources :orders, only: [:index, :show]
  patch 'orders/:id/update_status', to: 'orders#update_status', as: :update_status

  # Browse routes
  get 'restaurants', to: 'browse#index'
  get 'restaurants/:id', to: 'browse#show', as: :restaurant

  # Restaurant routes with nested resources for menu_items and reviews
  # resources :restaurants do
  #   resources :menu_items, only: [:index, :new, :create, :edit, :update, :destroy]
  #   resources :reviews, only: [:index, :new, :create, :edit, :update, :destroy]
  # end

  # Customer routes
  resources :customers, only: [:update, :show]
  resource :cart, only: [:show]
  get '/profile', to: 'profiles#show', as: :profile
  get '/edit_profile', to: 'profiles#edit', as: :edit_profile

  # MenuItems routes
  #resources :menu_items, only: [:show, :edit, :update, :destroy]

  # Defines the root path route ("/")
  # root "posts#index"
  resources :restaurants, only: [:index, :create, :update, :destroy] do
    resources :menu_items, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :reviews, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  get 'restaurants/:restaurant_id/customer_menu', to: 'menu_items#customer_index', as: :customer_menu
  post 'add_to_cart/:menu_item_id', to: 'cart_items#add_to_cart', as: :add_to_cart
  patch 'remove_from_cart/:menu_item_id', to: 'cart_items#remove_from_cart', as: :remove_from_cart
  get '/cartback', to: 'carts#back', as: :cart_back
  delete 'clear_cart', to: 'carts#clear_cart'

  # Owner path only
  get '/menu_items', to: 'menu_items#index'

  resource :checkout, only: [:create], controller: 'checkouts' do
    collection do
      get 'success', to: 'checkouts#success'
      get 'cancel', to: 'checkouts#cancel'
    end
  end

  get 'stripe_callback', to: 'stripe#callback'

  get 'owners/confirm', to: 'owners/registrations#confirm'
  get '*path', to: redirect('/home')

  resources :cart_items, only: [:create, :destroy]



end

app/models/restaurant.rb
# app/models/restaurant.rb

class Restaurant < ApplicationRecord
  PHONE_REGEX = /\A(\+1|1)?[-.\s]?(\()?(\d{3})(?(2)\))[-.\s]?(\d{3})[-.\s]?(\d{4})\z/

    has_many :carts, dependent: :destroy
    has_many :reviews, dependent: :destroy
    has_many :orders, dependent: :destroy
    has_many :menu_items, dependent: :destroy
    belongs_to :user

    has_many :customers, through: :orders

    validates :name, presence: { on: :create }
    validates :phone_number, presence: { on: :create }
    validates :address, presence: { on: :create }
    validates :description, presence: { on: :create }
    validates :operating_hours, presence: { on: :create }

    # validates :email, format: { with: URI::MailTo::EMAIL_REGEXP, message: "is not a valid email address" }, if: -> { email.present? }
    validates :phone_number, format: { with: PHONE_REGEX, message: "is not a valid US phone number" }, if: -> { phone_number.present? }
    validates :name, length: { maximum: 50 }, if: -> { name.present? }
    validates :address, length: { minimum: 10, maximum: 100 }, if: -> { address.present? }
    before_save :reformat_phone_number

    def reformat_phone_number
      digits = phone_number.scan(/\d+/).join # Extract all digits
      digits = digits[1..10] if digits.length == 11
      self.phone_number = "#{digits[0..2]}-#{digits[3..5]}-#{digits[6..9]}" if digits.length == 10
    end

  end

app/controllers/restaurants_controller.rb
# app/controllers/restaurants_controller.rb

class RestaurantsController < ApplicationController
  before_action :filter_blank_params, only: [:update]


    def update
      @restaurant = current_user.restaurant

      @restaurant.update(restaurant_params)
      redirect_to profile_path
    end

    def restaurant_params
      params.require(:restaurant).permit(:name, :phone_number, :address, :description, :operating_hours)
    end

    def filter_blank_params
      params[:restaurant].each do |key, value|
        params[:restaurant][key] = current_user.restaurant[key] if value.blank?
      end
    end

  end

app/views/restaurants/_field_form.html.erb
<%= form_with(model: @restaurant, local: true) do |form| %>
  <%= form.label label %>
  <%= form.text_field field %>
  <%= form.submit "Save" %>
<% end %>

app/views/restaurants/_rest_info.html.erb
<%= turbo_frame_tag "restaurant_name" do %>
    <h1><%= @restaurant.name %> 
        <%if current_user.restaurant == @restaurant%>
            <%= link_to '*', edit_profile_path %> 
        <%end%>
    </h1>
<%end%>
<%= turbo_frame_tag "restaurant_description" do %>
    <p><%= @restaurant.description %> 
        <%if current_user.restaurant == @restaurant%>
            <%= link_to '*', edit_profile_path %> 
        <%end%>
    </p>
<%end%>
<%= turbo_frame_tag "restaurant_address" do %>
    <p>Address: <%= @restaurant.address %> 
        <%if current_user.restaurant == @restaurant%>
            <%= link_to '*', edit_profile_path %> 
        <%end%>
    </p>
<%end%>
<%= turbo_frame_tag "restaurant_phone_number" do %>
    <p>Phone Number: <%= @restaurant.phone_number %> 
        <%if current_user.restaurant == @restaurant%>
            <%= link_to '*', edit_profile_path %> 
        <%end%>
    </p>
<%end%>
<%= turbo_frame_tag "restaurant_operating_hours" do %>
    <p>Operating Hours: <%= @restaurant.operating_hours %> 
        <%if current_user.restaurant == @restaurant%>
            <%= link_to '*', edit_profile_path %> 
        <%end%>
    </p>
<%end%>



<!-- <%= link_to 'View Menu', customer_menu_path(restaurant_id: @restaurant.id), class: 'btn btn-primary' %> -->

app/views/restaurants/edit.html.erb
<div>
  
  <h1>Edit Restaurant Information</h1>
  <%= turbo_frame_tag "restaurant_name" do %>
    <%= render 'restaurants/field_form', label: '', field: :name %>
  <% end %>
  <%= turbo_frame_tag "restaurant_description" do %>
    <%= render 'restaurants/field_form', label: '', field: :description %>
  <% end %>
  <%= turbo_frame_tag "restaurant_address" do %>
    <%= render 'restaurants/field_form', label: 'Address:', field: :address %>
  <% end %>
  <%= turbo_frame_tag "restaurant_phone_number" do %>
    <%= render 'restaurants/field_form', label: 'Phone Number:', field: :phone_number %>
  <% end %>
  <%= turbo_frame_tag "restaurant_operating_hours" do %>
    <%= render 'restaurants/field_form', label: 'Operating Hours:', field: :operating_hours %>
  <% end %>

</div>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>


  <p class="lead"></p>
  <table class="table">
    <thead>
      <tr>
        <th>Restaurant Name</th>
      </tr>
    </thead>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td> <%= link_to restaurant.name, restaurant_path(restaurant) %></td>
      </tr>
    <% end %>
  </table>
  <br>
  <%=link_to "Create new restaurant", new_restaurant_path %>
</section>

app/views/restaurants/new.html.erb
<!-- app/views/restaurants/new.html.erb -->

<!-- 
<h1>New Restaurant</h1>

<%= form_for @restaurant do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>
      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_area :address %>
  </div>

  <div class="field">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %>
  </div>

  <div class="field">
    <%= f.label :operating_hours %>
    <%= f.text_field :operating_hours %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', restaurants_path %>
-->

app/views/restaurants/newrestaurant.html.erb
<!-- app/views/restaurants/newrestaurant.html.erb -->

<h1>New Restaurant</h1>

<%= form_for @restaurant do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>
      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_area :address %>
  </div>

  <div class="field">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %>
  </div>

  <div class="field">
    <%= f.label :operating_hours %>
    <%= f.text_field :operating_hours %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/profile.html.erb
<%= render 'restaurants/rest_info'%>

<%= button_to 'Sign out', destroy_user_session_path, method: :delete %>
<%= link_to 'Edit_login', edit_customer_registration_path%>

<h2>Reviews</h2>

<% @reviews.each do |review| %>
  <div class="review">
    <p><strong>Customer:</strong> <%= review.customer.name %> Stars</p>
    <p><strong>Rating:</strong> <%= review.rating %> Stars</p>
    <p><%= review.comment %></p>
    <p><%= review.recorded_date %></p>
    
  </div>
<% end %>

<%= link_to 'View All Reviews', restaurant_reviews_path(@restaurant), class: 'btn btn-primary' %>

app/views/restaurants/show.html.erb
<h2>Details for <%= @restaur.name %></h2>

<section id="main" class="container">

  <p class="lead"></p>
  <dl>
    <dt>Description:
      <dd> <%= @restaur.description %>
    <dt>Address:
      <dd> <%= @restaur.address %>
    <dt>Phone number:
      <dd> <%= @restaur.phone_number %>
    <dt>Operating hours:
      <dd> <%= @restaur.operating_hours %>
  </dl>

  <%= link_to "Back to restaurant list", restaurants_path, class: "btn btn-primary" %>

</section>